// 展旭紀錄資料庫
const records = {
  
  "1": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": [],
    "31": []
  },

  "2": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [] // 只會在閏年有效
  },

  "3": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": [],
    "31": []
  },

  "4": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [
      { type: "link", content: "https://photos.app.goo.gl/piYWLwCRQufqTx3B8", label: "2016年4月17日 搭公車前往謝師宴" }
    ],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": []
  },

  "5": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": [],
    "31": []
  },

  "6": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": []
  },

  "7": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [
      { type: "link", content: "https://photos.app.goo.gl/B9e7yFksC4vg4YaZ8", label: "2016年7月22日 死都不會如此痛苦 獨角戲罷了沒有意義" }
    ],
    "23": [
      { type: "link", content: "https://photos.app.goo.gl/xr3WGedek85w98C27", label: "2016年7月23日 原來是個廢到底的垃圾 一點一滴回想著檢討著" }
    ],
    "24": [],
    "25": [],
    "26": [
      { type: "link", content: "https://photos.app.goo.gl/XpJ6R4QR2tKSc96A6", label: "2016年7月26日 在茫然中 前進...思考...徹底反思..." }
    ],
    "27": [],
    "28": [],
    "29": [],
    "30": [],
    "31": []
  },

  "8": {
    "1": [],
    "2": [
      { type: "link", content: "https://photos.app.goo.gl/JsSfHAdcxeAm76Hk7", label: "2016年8月2日 腸胃內科 實習 第一天" }
    ],
    "3": [],
    "4": [
      //{ type: "text", content: "測試文字" },
      { type: "link", content: "https://photos.app.goo.gl/nsukrSJaPRh8LTmD8", label: "2016年8月4日 等著上社會新聞頭版 家裡開中藥店 等著被砸店" },
      { type: "link", content: "https://photos.app.goo.gl/xTMABD1L8PYto82y7", label: "2016年8月4日 我會先剁你手 不要懷疑" }
    ],
    "5": [
      { type: "link", content: "https://photos.app.goo.gl/Qh57F5GRnVFLMPFn6", label: "2016年8月5日 原諒滿腦精蟲的畜牲 我做得到嗎？也許無法 後悔沒用 先自愛" },
      { type: "link", content: "https://photos.app.goo.gl/pvZKiFYrvdBhbveZ6", label: "2016年8月5日 只是想認真當個好醫生 如果有什麼能證明真愛 我想那是極端的痛苦" }
    ],
    "6": [],
    "7": [],
    "8": [
      { type: "link", content: "https://photos.app.goo.gl/fTcSU97ZJp2H8Uyy8", label: "2016年8月8日 痛苦的值班 痛苦的日子 我還沒放棄" }
    ],
    "9": [],
    "10": [],
    "11": [
      { type: "link", content: "https://photos.app.goo.gl/uWJ4b3NosNxoTzxy6", label: "2025年8月11日 直行車佔用轉彎專用車道" },
      { type: "link", content: "https://photos.app.goo.gl/a1LrepZJREGDXndZ6", label: "2016年8月11日 一人做事一人擔" }
    ],
    "12": [],
    "13": [],
    "14": [],
    "15": [
      { type: "link", content: "https://photos.app.goo.gl/cKcCD72FPVYUakZm8", label: "2016年8月15日 從我身上割下一塊血淋淋的肉" },
      { type: "link", content: "https://photos.app.goo.gl/5gFB53sSVrwq5tpcA", label: "2016年8月15日 究竟還要多久才能找到生命中的平靜" }
    ],
    "16": [],
    "17": [],
    "18": [],
    "19": [
      { type: "link", content: "https://photos.app.goo.gl/UMxiFyVWNVJrCtEH6", label: "2016年8月19日 默默寫下今天滿溢的情緒 我會振作" }
    ],
    "20": [],
    "21": [
      { type: "link", content: "https://photos.app.goo.gl/vCc7GpHwso5W2aHcA", label: "2016年8月21日 骨科的日子只有苦 苦的日子只有自己知道" }
    ],
    "22": [
      { type: "link", content: "https://photos.app.goo.gl/isto48x1XKz3AZgJA", label: "2016年8月22日 夜騎 台北 騎個夜台北" }
    ],
    "23": [
      { type: "link", content: "https://photos.app.goo.gl/RnybMSPhrLZAm4gLA", label: "2016年8月23日 錯過了就可能會永遠錯過 只是會有一個人需要帶著傷痛走下去" }
    ],
    "24": [],
    "25": [
      { type: "link", content: "https://photos.app.goo.gl/ke5QpEDaejFfe4cZ6", label: "2016年8月25日 小練重訓第30天不間斷" }
    ],
    "26": [
      { type: "link", content: "https://photos.app.goo.gl/yyfAeHB5BpyXM8sbA", label: "2016年8月26日 看透了灰暗面 也要收起玻璃心" }
    ],
    "27": [
      { type: "link", content: "https://photos.app.goo.gl/Dien47o2pDWhSRaf9", label: "2025年8月27日 不緊靠道路右側停車" }
    ],
    "28": [
      { type: "link", content: "https://photos.app.goo.gl/f1rwDgUAbNhcK2P36", label: "2016年8月28日 今晚喝酒其它都不要想了" }
    ],
    "29": [],
    "30": [
      { type: "link", content: "https://photos.app.goo.gl/8rFBUsxYktoPxxY26", label: "2016年8月30日 我好像魯夫 在被敵人摧殘了數次之後 依然頑固的拖著滿身血爬起來" }
    ],
    "31": []
  },

  "9": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [
      { type: "link", content: "https://photos.app.goo.gl/WFTsJ35TY95XPyuj8", label: "2025年9月21日 跟Barry比心電圖目前大輸五分追得上嗎" },
      { type: "link", content: "https://photos.app.goo.gl/zHXyt9AkmptewenHA", label: "2025年9月21日 ECG進階課程真的太精彩實用 專家就是把細節看到骨子裏" },
      { type: "link", content: "https://photos.app.goo.gl/UQQuKCYz8T52F1yAA", label: "2025年9月21日 週末一早被鞭策來上課" },
      { type: "link", content: "https://photos.app.goo.gl/vvYCMRC4UVUGBxXw5", label: "2025年9月21日 他兒子超有天份欸" },
      { type: "link", content: "https://photos.app.goo.gl/qTvvtCzhjgCJ1DmaA", label: "2024年9月21日 芒果軟糖 超級愛吃 希望以後能再回越南" },
      { type: "link", content: "https://photos.app.goo.gl/AG6j6LgVZLYYmAnL7", label: "2023年9月21日 想當年入伍訓是在地上爬旁邊引爆炸彈" },
      { type: "link", content: "https://photos.app.goo.gl/AWqoRNuSJ9M6akqp6", label: "2022年9月21日 I don't like to much ketone in my body" },
      { type: "link", content: "https://photos.app.goo.gl/25KjWZ5rkbgYrLh78", label: "2021年9月21日 大推的腳架清理&修理" },
      { type: "link", content: "https://photos.app.goo.gl/dHMdgjZiP4qwx34n7", label: "2020年9月21日 內心都有天使與惡魔交戰 不爭氣的用自己睡覺時間認命開" }
    ],
    "22": [
      { type: "link", content: "https://photos.app.goo.gl/DhDkFTv8pdhVSgXn9", label: "2024年9月22日 對國家沒貢獻的嘴砲對國家有貢獻的人" },
      { type: "link", content: "https://photos.app.goo.gl/pnZ4NQ2HgVSoaTBN6", label: "2024年9月22日 健身完就是直接約永豆" },
      { type: "link", content: "https://photos.app.goo.gl/ERN5qLZmFcvpoTAZA", label: "2023年9月22日 南京復興站真的很愛你 一定要趁被拆下來之前趕快去合照" },
      { type: "link", content: "https://photos.app.goo.gl/TowJEBhtvFCuQqXu9", label: "2023年9月22日 下午小補眠一下還是全身無力 要檢查每週一跑真的很困難" },
      { type: "link", content: "https://photos.app.goo.gl/gwhDj5wU8wXW4eBr9", label: "2022年9月22日 氣切管的氣囊壓力" },
      { type: "link", content: "https://photos.app.goo.gl/bQsAft4LoTbGVF4L7", label: "2019年9月22日 離開營區就像入獄後能短暫假釋 繼續逆著大浪 慢慢成長茁壯" },
      { type: "link", content: "https://photos.app.goo.gl/aAR699nw4GVuKCb79", label: "2017年9月22日 這才是生活 但是它很短暫 此生發誓及早退休" },
      { type: "link", content: "https://photos.app.goo.gl/uDAT7pPpgyNfTvZi9", label: "2016年9月22日 連續完全沒坐下上刀九個小時解鎖 nolimit" }
    ],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": []
  },

  "10": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": [],
    "31": []
  },

  "11": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [
      { type: "link", content: "https://photos.app.goo.gl/5uxQhntJZdxREUah7", label: "2016年11月11日 夠綠了還抽綠菸" }
    ],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": []
  },

  "12": {
    "1": [],
    "2": [],
    "3": [],
    "4": [],
    "5": [],
    "6": [],
    "7": [],
    "8": [],
    "9": [],
    "10": [],
    "11": [],
    "12": [],
    "13": [],
    "14": [],
    "15": [],
    "16": [],
    "17": [],
    "18": [],
    "19": [],
    "20": [],
    "21": [],
    "22": [],
    "23": [],
    "24": [],
    "25": [],
    "26": [],
    "27": [],
    "28": [],
    "29": [],
    "30": [],
    "31": []
  }

};
